### ISSUE TITLE
update to latest abapGit?

### ISSUE THREAD

**Issue by larshp** [sbcgua/abap_mustache#1]
Hi Alexander,
It looks like the XML files are not serialized using the latest version of abapGit? It should ignore the initial fields in the XML

**Comment by sbcgua** [comment]
Yeah, I will. 
I wanted to work on https://github.com/larshp/abapGit/issues/514 first, but couldn't get my hands on it yet. I've got a funny repo state after some experiments which surfaces the issue (or some other one, not sure ;) and I don't want to loose it. So I don't want to overwrite that repo with new format. 

BTW what do you think about using mustache in abapGit ?

P.S. First issue ! :tada:

**Comment by sbcgua** [comment]
updated XMLs
@larshp: BTW what do you think about using mustache in abapGit ?

**Comment by larshp** [comment]
mustache is cool, but I'm afraid of adding more frameworks, as contributors would need to also get familiar with it before being able to create a page. Whereas most people hopefully already know HTML
