### ISSUE TITLE
Bug in demo program (boolc)

### ISSUE THREAD

**Issue by der-david** [sbcgua/abap_mustache#10]
Hi,

the following line in the `ZABAP_MUSTACHE_RUNNER` demo always results in the output `Good afternoon` on my system (750-0019).
https://github.com/sbcgua/abap_mustache/blob/cb1f3ff41e66877779944b0d3a4015d8bbbdf6d1/src/zabap_mustache_runner.prog.abap#L41

As we all know, ABAP is a bit nitpicky with comparisons and booleans.
`boolc` returns a string which is not technically initial, if the condition is not met (see [ABAP Keyword Documentation](https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abenboole_functions.htm)). That prevents `ZCL_MUSTACHE_RENDER=>EVAL_CONDITION` from returning the "correct" result.

**There is nothing wrong with the library itself**, but using `xsdbool` instead of `boolc` in the demo fixes this issue which left me a little confused and hesitant to use ABAP Mustache after the first run.

**Comment by sbcgua** [comment]
Thanks for the issue, and sorry for long response :)
Indeed, it was a bug. I'd like to keep compatibility with <7.40 which does not have `xsdbool` so I adjusted the code in another way. But I hope it work now. Thanks again for the logged issue.
