### ISSUE TITLE
Not ready for ABAP for Cloud Development 

### ISSUE THREAD

**Issue by ruthiel** [sbcgua/abap_mustache#13]
Hello @sbcgua !
Thanks a lot for your wonderful development!

I've tried your solution on a ABAP Environment instance. 
There I have to use the new version of ABAP -> **ABAP for Cloud Development**

There are a couple of instructions that not work at all in this version, as **DESCRIBE FIELDS**, **GET REFERENCE**, macros, etc.

I adapted the code hence the solution is already working fine here!

Let me know if you need help to prepare the code for **ABAP for Cloud Development**!

Thanks!

**Comment by sbcgua** [comment]
Hi, @ruthiel , glad that you enjoyed it :)

PR's are welcomed :) But did you also try the steampunk branch here: https://github.com/sbcgua/abap_mustache/tree/steampunk ? It was reworked to remove macros and `describe field`

**Comment by ruthiel** [comment]
Ohhh! 

Thank you for your clarification @sbcgua !

I just didn't noticed the specific branch for steampunk! 

Solved! 

Best wishes!
